### ISSUE TITLE
[Issue] creator退出时不解散round (by weiyuhan)

### ISSUE THREAD

**Issue by Symbolk** [Symbolk/CrowdJigsaw#26]
### 问题描述
round人数凑不够时，creator想重开round所以退出，但退出后应该解散round，因为其他players也不能start

### 可能原因
round结束判断的问题

### 涉及代码
round.js--quitRound

**Comment by colligence** [comment]
一种解决方案：不用creator启动游戏；人数满足条件后，自动启动；当一段时间后人数还不够，该游戏自动取消。

**Comment by Symbolk** [comment]
对，而且join时不用再点击确定，这个也一并解决。
