### ISSUE TITLE
[Feature] round等待界面不够美观 （by zxy）

### ISSUE THREAD

**Issue by Symbolk** [Symbolk/CrowdJigsaw#28]
### 描述
round等待界面维护的用户列表太长，界面不友好

### 改进
只展示等待中players的名字，round信息放到一行，界面尽量简洁

**Comment by colligence** [comment]
可以在等待页面上只显式一个进度条。如果要看当前加入的人员信息，可以给一个链接弹出一个新页面。

**Comment by Symbolk** [comment]
我的想法是用点击展开这种方式，不用链接弹出。

**Comment by colligence** [comment]
点击更好。但要确保进度条还是在原来的位置，人员信息在进度条下面按照某种方式展示出来。
