### ISSUE TITLE
[Feature] 希望图片更加多样（by yuxia zhang）

### ISSUE THREAD

**Issue by Symbolk** [Symbolk/CrowdJigsaw#30]
### 描述
现在的图片多次试验后，熟悉度会影响公平性

### 改进
添加更多的经过选择的图片，比如CISE组的合照。

**Comment by colligence** [comment]
大家自己在北大内部拍一些相片，应该就不错。还不会有版权的问题。

**Comment by Symbolk** [comment]
对于图片选择还是有要求的，比如不能有大量空白或同色区域，因为拼图时块间区别是肉眼是无法分辨的。

**Comment by Symbolk** [comment]
![wechat image_20171206121103](https://user-images.githubusercontent.com/14107297/33644237-8eefe3e2-da7e-11e7-99e0-9ff2341c64e2.jpg)
这是我拍的一副照片，可能需要一定裁剪符合要求。

**Comment by colligence** [comment]
在地面上加上一些树叶，就可以用来拼图了。
