### ISSUE TITLE
[Feature] Round内排行榜 (by all)

### ISSUE THREAD

**Issue by Symbolk** [Symbolk/CrowdJigsaw#32]
### 描述
大家更关注round内的players排行

### 改进
增加round内排行榜，综合考虑贡献、步数、时间等。

**Comment by colligence** [comment]
一种简单的方式：第一次发现一条正确边的玩家得1分；然后设置一个衰减常数alpha (大于零，小于一)，第二次引用这个边的玩家得alpha分，第三次的玩家得“alpha的平方”分。依次类推。

**Comment by Symbolk** [comment]
当前实现的计算策略（alpha=0.8）：
操作   已执行过该操作的人数    contribution
++        0                                       +1
+           n                                      +alpha^n
--          0                                       -1
-            n                                      -alpha^n

**Comment by Symbolk** [comment]
某player进行游戏时，可以通过侧边栏查看当前在线玩家的贡献排行；
该player完成游戏时，可以选择回到Home或跳转到round排行：

此时已完成的player按{time,step} 升序+{contribution}降序排列，未完成用户按{contribution}降序排列（time和step显示为 N/A）
