### ISSUE TITLE
[兼容性问题] 需要确保在chrome, firefox, safari三种浏览器上的正常操作

### ISSUE THREAD

**Issue by colligence** [Symbolk/CrowdJigsaw#39]
这三种浏览器都是很现代的浏览器，对标准的遵从度也很高。

如果一个软件包不能兼容这三种浏览器，那么就换一个可以兼容的软件包。这应该不是一件困难的事情。

**Comment by Symbolk** [comment]
目前兼容性问题主要存在于round等待界面，用boostrap进行改写。

**Comment by colligence** [comment]
前端的CSS确实需要统一到boostrap上。现在很多页面/对话框的样式缺乏基本的美感/协调感。

**Comment by colligence** [comment]
目前无法做到，就只确保在chrome下能用吧。
