### ISSUE TITLE
[Feature Request] 增加对片段边缘像素的抹除功能

### ISSUE THREAD

**Issue by colligence** [Symbolk/CrowdJigsaw#48]
在分割图片时，可以给定一个整型参数x，表示需要把分割后的边缘像素抹除掉多少行/列。

实现时，等价于：先在原始图片的分割线上画上宽度为2x的纯色线条；然后再对图片进行分割。

**Comment by Symbolk** [comment]
已增加：
1，消除拼图块是否处于原图边际的信息（新建round时可选：是否保留edge info）
2，消除每个拼图块边缘n个像素信息。
